[package]
name = "anyrun-powermenu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyrun-plugin = "0.1.0"
abi_stable = "0.11.1"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.1"
fuzzy-matcher = "0.3.7"
